spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vk
    password: rcb
    url: jdbc:mysql://localhost:3306/buzqb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update