server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rcb88888
    url: jdbc:mysql://localhost:3306/buzqb
  redis:
    host: localhost
    port: 6379
    cache:
      type: redis
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 857689704790-k2mtbfm1gfm08ltda8pn6gr6a027k1nr.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
security:
  jwt:
    expiration-time: '7200000'
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b